import { NextRequest, NextResponse } from "next/server";
import { getTask } from "@/lib/taskStore";

/**
 * GET /api/generate/models/[taskId].glb
 * Serves the real GLB binary generated by Stable Fast 3D.
 */
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ taskId: string }> }
) {
  try {
    const { taskId } = await params;

    if (!taskId) {
      return NextResponse.json({ error: "Task ID required" }, { status: 400 });
    }

    // Strip the .glb extension if the route captured it
    const cleanId = taskId.replace(/\.glb$/i, "");
    const task = getTask(cleanId);

    if (!task) {
      return NextResponse.json({ error: "Task not found" }, { status: 404 });
    }

    if (task.status === "processing" || task.status === "pending") {
      return NextResponse.json(
        { error: "Model not ready yet", status: task.status, progress: task.progress },
        { status: 202 }
      );
    }

    if (task.status === "failed") {
      return NextResponse.json(
        { error: task.error ?? "Generation failed" },
        { status: 500 }
      );
    }

    if (!task.glbBuffer || task.glbBuffer.length === 0) {
      return NextResponse.json({ error: "GLB buffer not found" }, { status: 404 });
    }

    // Serve the real GLB
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return new Response(task.glbBuffer as any, {
      status: 200,
      headers: {
        "Content-Type": "model/gltf-binary",
        "Content-Length": task.glbBuffer.length.toString(),
        "Cache-Control": "private, max-age=3600",
        "Access-Control-Allow-Origin": "*",
      },
    });
  } catch (error) {
    console.error("[SF3D models] Error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Server error" },
      { status: 500 }
    );
  }
}
